version: '3.8'

services:
  drogon-db:
    image: postgres:15-alpine
    container_name: "drogon-db-1"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=lstfng
      - POSTGRES_PASSWORD=lstfng
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lstfng -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: