CREATE SCHEMA IF NOT EXISTS postgres;

CREATE TABLE IF NOT EXISTS users
(
    id          BIGSERIAL PRIMARY KEY,
    first_name  VARCHAR(50) DEFAULT NULL,
    last_name   VARCHAR(50) DEFAULT NULL,
    email       VARCHAR(255) UNIQUE NOT NULL,
    token       TEXT DEFAULT NULL,
    password    TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT NULL,
    is_deleted  BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS todo
(
    id          BIGSERIAL PRIMARY KEY,
    user_id     BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title       VARCHAR(75) NOT NULL,
    description TEXT DEFAULT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT NULL,
    is_completed BOOLEAN DEFAULT FALSE
);