/**
 *
 *  Todos.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Todos.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Todos::primaryKeyName = "";
const bool Todos::hasPrimaryKey = false;
const std::string Todos::tableName = "todos";

const std::vector<typename Todos::MetaData> Todos::metaData_={
};
const std::string &Todos::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Todos::Todos(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Todos::Todos(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Todos::Todos(const Json::Value &pJson) noexcept(false)
{
}

void Todos::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void Todos::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Todos::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Todos::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Todos::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Todos::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Todos::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Todos::toJson() const
{
    Json::Value ret;
    return ret;
}

std::string Todos::toString() const
{
    return toJson().toStyledString();
}

Json::Value Todos::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Todos::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Todos::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Todos::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Todos::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Todos::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
